[app]
46.21.247.207 ansible_user=user2 ansible_ssh_private_key_file=/home/user1/.ssh/id_rsa
130.193.39.125 ansible_user=user3 ansible_ssh_private_key_file=/home/user1/.ssh/id_rsa

[database]
localhost ansible_connection=local postgresql_version=12 postgresql_data_dir=/var/lib/postgresql/12/main

[web]
localhost asible_connection=local
